version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
  main-back:
    container_name: main-back
    restart: always
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  admin:
    container_name: admin
    restart: always
    build: ./admin
    ports:
      - "1000:1000"
    volumes:
      - .:/app
  main:
    container_name: main
    restart: always
    build: ./main
    ports:
      - "1100:1100"
    volumes:
      - .:/app
